wandb_version: 1

num_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0006
weight_decay:
  desc: null
  value: 0.1
rc_aug:
  desc: null
  value: true
add_eos:
  desc: null
  value: false
model_name:
  desc: null
  value: hyenadna-tiny-1k-seqlen
dataset_name:
  desc: null
  value: human_ocr_ensembl
max_length:
  desc: null
  value: 400
n_classes:
  desc: null
  value: 2
random_seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742838074
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.17.2
      6: 4.26.1
      8:
      - 8
      13: linux-x86_64
