wandb_version: 1

num_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0006
weight_decay:
  desc: null
  value: 0.1
rc_aug:
  desc: null
  value: true
add_eos:
  desc: null
  value: false
world_size:
  desc: null
  value: 2
model_configs:
  desc: null
  value:
    hyenadna-tiny-1k-seqlen:
      pretrained: true
      config: null
dataset_metadata:
  desc: null
  value:
    dummy_mouse_enhancers_ensembl:
      max_length: 1000
      n_classes: 2
    demo_coding_vs_intergenomic_seqs:
      max_length: 200
      n_classes: 2
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742348543
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.11.6
      5: 0.17.9
      6: 4.26.1
      8:
      - 5
      13: linux-x86_64
