wandb_version: 1

num_epochs:
  desc: null
  value: 50
max_length:
  desc: null
  value: 4400
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0006
weight_decay:
  desc: null
  value: 0.1
rc_aug:
  desc: null
  value: true
use_padding:
  desc: null
  value: true
add_eos:
  desc: null
  value: false
warmup_epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740702085
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.11.6
      5: 0.17.9
      6: 4.26.1
      8:
      - 5
      13: linux-x86_64
device:
  desc: null
  value: cuda:0
